
pull_request_rules:
  - name: dependabot
    conditions:
      - and:
        - -draft
        - base=main
        - -closed
        - -conflict
        - label=dependencies
        - author=dependabot[bot]
        - check-success=Build
    actions:
      merge:
        method: merge